version: "3.9"

services:
  app:
    build: .
    environment:
      DOCKER: "Enabled"
    depends_on:
      - selenium
    volumes:
      - ./:/app/config

  selenium:
    image: selenium/standalone-chrome