version: "3.9"

services:
  app:
    image: semikolondev/itech-auto-attendance:1.0.0
    environment:
      DOCKER: "Enabled"
    depends_on:
      - selenium
    volumes:
      - appsetting.json/:/app/config/appsettings.json

  selenium:
    image: selenium/standalone-chrome
    shm_size: "2g"